version: "2"
services:
  varnish:
    image: meanbee/magento2-varnish:latest
    ports:
      - 80
    links:
      - web

  web:
    image: meanbee/magento2-nginx:1.9
    ports:
      - 80
    links:
      - fpm
      - db
    volumes_from:
      - appdata
    env_file:
      - ./global.env

  fpm:
    hostname: fpm.magento2.docker
    image: meanbee/magento2-php:7.2-fpm
    ports:
      - 9000
    links:
      - db
      - redis
      - rabbitmq
      - elasticsearch
    volumes_from:
      - appdata
    env_file:
      - ./global.env
    # environment:
      #- XDEBUG_CONFIG=remote_connect_back=0 remote_host=172.17.0.1
      #- PHP_IDE_CONFIG=serverName=magento2.docker
      #- PHP_ENABLE_BLACKFIRE=false

  db:
    image: mariadb:10
    ports:
      - 3306
    volumes_from:
      - dbdata
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - TERM=meh

  cli:
    hostname: cli.magento2.docker
    image: meanbee/magento2-php:7.2-cli
    links:
      - db
      - redis
      - rabbitmq
      - elasticsearch
    volumes:
      - ~/.composer/cache:/root/.composer/cache
    volumes_from:
      - appdata
    env_file:
      - ./global.env
      - ./composer.env
    environment:
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_DB_HOST=db
      - M2SETUP_DB_NAME=magento2
      - M2SETUP_DB_USER=magento2
      - M2SETUP_DB_PASSWORD=magento2
      - M2SETUP_BASE_URL=http://magento2.docker/
      # - M2SETUP_SECURE_BASE_URL=https://magento2.docker/
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=password1
      - M2SETUP_VERSION=2.3.*
      # - M2SETUP_USE_SAMPLE_DATA=true
      # - PHP_ENABLE_XDEBUG=false

  elasticsearch:
    image: elasticsearch:6.8.0
    ports:
      - 9200
      - 9300
    volumes_from:
      - appdata
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:6.8.0
    ports:
      - 5601
    links:
      - elasticsearch
    volumes_from:
      - appdata
    environment:
      SERVER_NAME: kibana.magento2.docker
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200/

  redis:
    image: redis:latest
    ports:
      - 6379
    volumes_from:
      - appdata

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672
      - 15672
    volumes_from:
      - appdata

  cron:
    image: meanbee/magento2-php:7.2-cli
    hostname: magento2-cron.docker
    command: run-cron
    env_file:
      - ./global.env    
    environment:
      - ENABLE_SENDMAIL=true
    volumes_from:
      - appdata
    links:
      - db
    env_file:
      - ./global.env      

  appdata:
    image: tianon/true
    volumes:
      - ./magento:/var/www/magento

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql
